name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  add_to_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: resume-*
          path: out
          merge-multiple: true

      - name: Attach files to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            out/*.pdf
            out/*.md
            *.json
          fail_on_unmatched_files: true